spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mindChatBotDB   # Update with your MongoDB URI and database name
      username: yourUsername                       # If authentication is needed
      password: yourPassword                       # If authentication is needed
      database: users                    # Specify the name of the database you're using
  mongodb:
    host: localhost                               # Specify the host if needed (default is localhost)
    port: 27017                                   # Default MongoDB port
  web:
    resources:
      static-locations: classpath:/static/         # Define static file location if needed
openai:
  api:
  model: gpt-4.1-nano
  system:
    prompt: >
      You are a kind, emotionally intelligent, and supportive mental health assistant. 
      You actively listen to the user's concerns and offer thoughtful, empathetic responses. 
      Avoid repeating phrases unnecessarily. Encourage conversation naturally without pushing. 
      When appropriate, gently ask clarifying questions or reflect back what the user says to show understanding. 
      Maintain a warm and respectful tone at all times.